**Complete the code to return the output**

In [ ]:
moons = {'earth': 1, 'mars': 2}
? = 67
print(moons)
# Required Output: {'earth': 1, 'mars': 2, 'jupiter': 67}

In [1]:
moons = {'earth': 1, 'mars': 2}
moons['jupiter'] = 67
print(moons)

{'earth': 1, 'mars': 2, 'jupiter': 67}

**Complete the code to return the output**

In [9]:
import pandas as pd
product=['A','A','A','B','B','B']
month=['Jan','Feb','Mar','Jan','Feb','Mar']
sold=[85,200,180,90,80,130]
sales=pd.DataFrame(product,month,sold)
print(sales)

ValueError: Shape of passed values is (6, 1), indices imply (6, 6)

In [ ]:
Following is a preview of the DataFrame sales:

product month sold
      A   Jan   85
      A   Feb  200
      A   Mar  180
      B   Jan   90
      B   Feb   80
      B   Mar  130

In [ ]:
import numpy as np
pick = np.logical_or(sales['product'] == 'B',?)
sales[pick]
---
""""Required Output:
product month  sold
1       A   Feb   200
2       A   Mar   180
3       B   Jan    90
4       B   Feb    80
5       B   Mar   130
""""

In [6]:
import numpy as np
pick = np.logical_or(sales['product'] == 'B',sales.loc['product'])
sales[pick]
---

'\nComentario\n'

In [1]:
dataCamp={'chapter':[1,2,3],'course':['Ds','Dv','D'],'technology':['Python','R','SQL']}

In [2]:
print(dataCamp)

{'chapter': [1, 2, 3], 'course': ['Ds', 'Dv', 'D'], 'technology': ['Python', 'R', 'SQL']}

In [3]:
import pandas as pd
dataCamp_df=pd.DataFrame(dataCamp)

In [6]:
dataCamp_df.index=['P','R','S']

In [7]:
dataCamp_df

   chapter course technology
P        1     Ds     Python
R        2     Dv          R
S        3      D        SQL

In [8]:
for lab, row in dataCamp_df.iterrows():
  print(lab + " - " + row["technology"])

P - Python
R - R
S - SQL

In [10]:
i = -4
while i != 0:
    if i>0:
        i -= 1
    else: 
        i += 1
        print(i)

-3
-2
-1
0

In [12]:
rotation_period = {
    'earth': 1.0,
    'jupiter': 0.415, 
    'saturn': 44}
rotation_period['saturn']=0.445
print(rotation_period)

{'earth': 1.0, 'jupiter': 0.415, 'saturn': 0.445}

In [14]:
x = 6
if x % 2 == 0:
    print("x is even")

x is even

In [15]:
dataCamp_df.loc[["P", "S"]]

   chapter course technology
P        1     Ds     Python
S        3      D        SQL

In [19]:
dataCamp_df.iloc[[1], 0]

R    2
Name: chapter, dtype: int64

In [21]:
type(dataCamp_df.iloc[[1], 0])

pandas.core.series.Series

In [22]:
dataCamp_df.iloc[[1], [0]]

   chapter
R        2

In [23]:
type(dataCamp_df.iloc[[1], [0]])

pandas.core.frame.DataFrame

In [2]:
import numpy as np
df=[[1,2],[3,4],[5,6]]
np_df=np.array(df)
print(np_df)

[[1 2]
 [3 4]
 [5 6]]

In [4]:
array([1,2,3])

NameError: name 'array' is not defined

In [5]:
sorted([-1,3,-2], reverse = True)

[3, -1, -2]

In [6]:
x = [False, True, '2', 3.0]
print(type(x))

<class 'list'>

In [7]:
q = [37, 26, 0, 30, 21, 11]
print(len(q))

6